language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
before_install:
  make create_github_status
deploy:
  provider: surge
  skip_cleanup: true
  domain: scharfer.surge.sh
  project: ./build/
on:
  branch:master